name = "ChunkCodecLibBlosc"
uuid = "c6a955be-ab7f-4fbb-b38f-caf93db6b928"
authors = ["nhz2 <nhz2@cornell.edu>"]
version = "0.1.1"

[deps]
Blosc_jll = "0b7ba130-8d10-5ba8-a3d6-c5182647fed9"
ChunkCodecCore = "0b6fb165-00bc-4d37-ab8b-79f91016dbe1"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
Blosc_jll = "1"
ChunkCodecCore = "0.4"
julia = "1.10"
