name = "ChunkCodecLibAec"
uuid = "50eb285c-f72d-40fd-bb37-8ab277ca8a2c"
authors = ["nhz2 <nhz2@cornell.edu>"]
version = "0.1.1"

[deps]
ChunkCodecCore = "0b6fb165-00bc-4d37-ab8b-79f91016dbe1"
libaec_jll = "477f73a3-ac25-53e9-8cc3-50b2fa2566f0"

[compat]
ChunkCodecCore = "0.5.1"
libaec_jll = "1"
julia = "1.7"

[workspace]
projects = ["test"]
