name = "ChunkCodecs"
uuid = "cea5061e-088a-433e-a623-54fa23d14d8f"
authors = ["nhz2 <nhz2@cornell.edu>"]
version = "0.1.0"

[deps]
ChunkCodecLibBlosc = "c6a955be-ab7f-4fbb-b38f-caf93db6b928"
ChunkCodecCore = "0b6fb165-00bc-4d37-ab8b-79f91016dbe1"
ChunkCodecLibBzip2 = "2b723af9-f480-4e8d-a1e4-4a9f5a906122"
ChunkCodecLibLz4 = "7e9cc85e-5614-42a3-ad86-b78f920b38a5"
ChunkCodecLibZlib = "4c0bbee4-addc-4d73-81a0-b6caacae83c8"
ChunkCodecLibZstd = "55437552-ac27-4d47-9aa3-63184e8fd398"

[compat]
ChunkCodecLibBlosc = "0.1"
ChunkCodecCore = "0.4"
ChunkCodecLibBzip2 = "0.1"
ChunkCodecLibLz4 = "0.1"
ChunkCodecLibZlib = "0.1"
ChunkCodecLibZstd = "0.1"
julia = "1.11"

[sources]
ChunkCodecCore = {path = "../ChunkCodecCore"}
ChunkCodecLibBlosc = {path = "../LibBlosc"}
ChunkCodecLibBzip2 = {path = "../LibBzip2"}
ChunkCodecLibLz4 = {path = "../LibLz4"}
ChunkCodecLibZlib = {path = "../LibZlib"}
ChunkCodecLibZstd = {path = "../LibZstd"}
