name = "ChunkCodecCore"
uuid = "0b6fb165-00bc-4d37-ab8b-79f91016dbe1"
authors = ["nhz2 <nhz2@cornell.edu>"]
version = "0.4.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
julia = "1.10"
