name = "ChunkCodecTests"
uuid = "06b1ce50-b741-4199-b118-ba5fe1a70fa7"
authors = ["nhz2 <nhz2@cornell.edu>"]
version = "0.1.0"

[deps]
ChunkCodecCore = "0b6fb165-00bc-4d37-ab8b-79f91016dbe1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
ChunkCodecCore = {path = "../ChunkCodecCore"}

[compat]
ChunkCodecCore = "0.2"
Test = "1"
julia = "1.11"